version: "3.7"
services:
  localstack:
    container_name: awslocal
    image: localstack/localstack-full:latest
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=1
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOVE_CONTAINERS=true
#      - HOSTNAME_EXTERNAL=awslocal
#      - HOSTNAME=awslocal
#      - DATA_DIR=/tmp/localstack/data
#      - START_WEB=1
#    volumes:
#      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"